name: Product Column Slider
description: 
enabled_text: false
required_text: false
enabled_link: false
enabled_image: false
css:
    -
      path: views/templates/front/productcolumnslider/css/productcolumnslider.css
      priority: 200
      position: head
      server: local
js:
    -
      path: views/templates/front/productcolumnslider/js/productcolumnslider.js
      priority: 250
      media: screen
      server: local